# Generated by Django 2.2 on 2021-07-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='posted_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_posted', to='login_app.User'),
            preserve_default=False,
        ),
    ]
