# Generated by Django 2.2 on 2021-07-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users_favorite',
            field=models.ManyToManyField(related_name='favorite_recipes', to='login_app.User'),
        ),
    ]
